# Copyright © SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

name: Upload slint-compiler to Python Package Index

on:
  workflow_dispatch:
    inputs:
      release:
        type: boolean
        default: false
        required: false
        description: "Release? If false, publish to test.pypi.org, if true, publish to pypi.org"

jobs:
  wheel:
    strategy:
      matrix:
        platform:
          - kind: linux
            runner: ubuntu-22.04
            target: x86_64
            manylinux: auto
          - kind: linux
            runner: ubuntu-22.04
            target: aarch64
            manylinux: auto
          - kind: musllinux
            runner: ubuntu-22.04
            target: x86_64
            manylinux: musllinux_1_2
          - kind: musllinux
            runner: ubuntu-22.04
            target: aarch64
            manylinux: musllinux_1_2
          - kind: windows
            runner: windows-2022
            target: x64
            manylinux: ""
          - kind: windows
            runner: windows-2022
            target: x86
            manylinux: ""
          - kind: macos
            runner: macos-14
            target: aarch64
            manylinux: ""
    runs-on: ${{ matrix.platform.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          working-directory: tools/compiler
          target: ${{ matrix.platform.target }}
          args: --release --out dist
          sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
          manylinux: ${{ matrix.platform.manylinux }}
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.platform.kind }}-${{ matrix.platform.target }}
          path: tools/compiler/dist

  sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build sdist
        uses: PyO3/maturin-action@v1
        with:
          working-directory: tools/compiler
          command: sdist
          args: --out dist
      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: wheels-sdist
          path: tools/compiler/dist

  publish-to-test-pypi:
    if: ${{ github.event.inputs.release != 'true' }}
    needs: [wheel, sdist]
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/slint-compiler
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true
      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
  publish-to-pypi:
    if: ${{ github.event.inputs.release == 'true' }}
    needs: [wheel, sdist]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/slint-compiler
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true